#!/usr/bin/env bash

sudo cp lib/sublime-url-handler.desktop /usr/share/applications
sudo update-desktop-database

sudo cp lib/sublime-url-handler /usr/local/bin/
sudo chmod +x /usr/local/bin/sublime-url-handler
